# Generated by Django 4.2.7 on 2023-12-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review_tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=10000)),
                ('review', models.CharField(max_length=10000)),
                ('review_time', models.CharField(max_length=10000)),
                ('Cafeid', models.CharField(default='default', max_length=10000)),
                ('name', models.CharField(max_length=10000)),
                ('review_tokenization', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Store_labels',
            fields=[
                ('link', models.CharField(max_length=10000)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=1000)),
                ('img', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=500)),
                ('star', models.FloatField()),
                ('reivew_num', models.IntegerField()),
                ('labels', models.CharField(max_length=5000)),
            ],
        ),
    ]
