# Generated by Django 4.2.7 on 2023-12-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cafeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store_labels',
            old_name='reivew_num',
            new_name='review_num',
        ),
    ]
